name: Auto Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      # ================== 前端构建 ==================
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装前端依赖 & 构建
        run: |
          cd front-end
          npm install
          npm run build

      - name: 传输前端文件到服务器
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "front-end/build/*"
          target: "/money-book/front-end"
          strip_components: 1
